"""add gallery pages

Revision ID: 39cb0e78bf81
Revises: b1f25930b580
Create Date: 2026-08-24 19:35:50.735498

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39cb0e78bf81"
down_revision: str | Sequence[str] | None = "b1f25930b580"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gallery_id", sa.Uuid(), nullable=False),
        sa.Column("page_index", sa.Integer(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("modified_ns", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.CheckConstraint("page_index >= 0", name="ck_pages_page_index_nonnegative"),
        sa.CheckConstraint("size_bytes >= 0", name="ck_pages_size_bytes_nonnegative"),
        sa.ForeignKeyConstraint(["gallery_id"], ["galleries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gallery_id", "page_index", name="uq_pages_gallery_page_index"),
        sa.UniqueConstraint("gallery_id", "relative_path", name="uq_pages_gallery_relative_path"),
    )
    op.create_index("ix_pages_gallery_id", "pages", ["gallery_id"], unique=False)
    op.drop_constraint(op.f("gallery_status"), "galleries", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("gallery_status"), "galleries", "status IN ('active', 'missing', 'trashed')"
    )
    op.drop_index("ix_pages_gallery_id", table_name="pages")
    op.drop_table("pages")
    # ### end Alembic commands ###
